name: CI/CD - Main Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Install Dependencies (Backend)
        working-directory: ./backend
        run: npm install

      - name: Run Unit Tests (Frontend)
        working-directory: ./frontend
        run: npm test

      - name: Run Unit Tests (Backend)
        working-directory: ./backend
        run: npm test

      - name: Build Docker Images
        run: docker-compose build

      - name: Start Docker Containers
        run: docker-compose up -d

      - name: Install ChromeDriver and Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-xcb1 libnss3 libxss1 libappindicator3-1 fonts-liberation libasound2 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libxcomposite1 libxrandr2 xdg-utils
          npm install selenium-webdriver chromedriver mocha --save-dev

      - name: Run E2E Tests
        run: |
          npm test -- ./e2e-tests/test.js
        env:
          NODE_ENV: test

      - name: Stop Docker Containers
        if: always()
        run: docker-compose down

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Images
        if: success()
        run: docker-compose push
