name: CI/CD - Main Deployment

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Install Dependencies (Backend)
        working-directory: ./backend
        run: npm install

      - name: Run Unit Tests (Frontend)
        working-directory: ./frontend
        run: npm test

      - name: Run Unit Tests (Backend)
        working-directory: ./backend
        run: npm test

      - name: Build Docker Images
        run: docker-compose build

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Images
        run: docker-compose push
